### ISSUE TITLE
Add Requirements.txt for python dependencies

### ISSUE THREAD

**Issue by JustinMiehle** [marlaman/show-me#4]
Just tried to run this locally as it looks amazing!

Wanted to ask if the requirements.txt is missing from the backend folder or if i am confused - as i could not find any but it is mentioned in the readme.

Thanks for sharing this! Excited to try it out, will try to just install all needed dependencies myself in the meantime

**Comment by ashakoen** [comment]
Suggested a requirements.txt via https://github.com/marlaman/show-me/pull/5

This worked for me.

**Comment by JustinMiehle** [comment]
Thanks! Awesome!

**Comment by JustinMiehle** [comment]
Fixed by #5
